language: node_js
node_js:
  - "6"
  - "6.1"
  - "5"
  - "5.11"
  - "4"
  - "iojs"
before_script:
  - npm install
script: "npm run-script test-ci"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"