language: node_js
addons:
  code_climate:
    repo_token:
      secure: mUF46Q3Hga3APJZyr1Ol6rhCj9dTsCO3STwuk0CFkmdvuxmFS6yQX6l2kTBg5MSoGPekZYixoBXYGC3wcMj75eaKUDNA96Qe24sYU026R2jeHkz6wN86pYFeZmAPsUVKEJW39dcFzAB/ktbIPkO7mxBL8nR7e1HwkHohQFRotrkQTeRznDXhYc5SlSrv1P7ATLxs0L3xmwXh62Fe2J3bqSAZIhSBbgzNwao5mSR05iAZYIjMNHoDhOT58yps+LwhWHGifs62mjsL2Tc0zoj9CiUK29v/WyYj34G6d8Ru5bUvyqdNfQNNPUmU7OF9R4jADbQD+heet82MJpYkbUl6d3EQV8uXUWgrh622nGbmDL2Q2kZvhETQQkd65kmZ38Fwu/9RxAQwhkI1srb4xkNxpUWLrehMCWVus/AdWH5Ph7iTgpvxAntt5Tgx7XlkOvbviQHLdmu4cFHkXL1MvRH31GczSvbUMpkHCQ2fOi/VLW6+aW1UzC3Yqz8eJw7gCaD1b7ZdbrVnusU75RRGo9QWL8TVzF17erBwTqq+X8JnUI6OTkH3zKzBXct6fhy4IpvicB4TOhU0/Tc4mhSah+gkAI1yKE6UJDxqZnc0+Zd/KHt3G3EJQGlSSzBY8hpDoBXqsmL5cVD7lMZKurIAnhncqmthq50S5z23Y/q/Z+tYy7M=
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "6.1"
before_script:
  - npm install
  - npm install --
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: "npm run-script test-ci"
after_success:
  - "npm install coveralls && cat ./coverage/lcov.info | coveralls"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT