# Test against the latest version of this Node.js version
init:
  - git config --global core.autocrlf true
# Install scripts. (runs after repo cloning)
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test-ci

# Don't actually build.
build: off