export enum UserPermission {
    USERS_CREATE = 1,
    USERS_READ = 2,
    READ_QUERY_HISTORY = 3,
    READ_SUMMARY = 4,
    READ_CLIENT_HISTORY = 5,
    READ_TOP_CLIENTS = 6,
    READ_TOP_ADS = 7,
    READ_TOP_DOMAINS = 8,
    READ_QUERY_LOG = 9,
    READ_OWN_QUERY_LOG = 10,
    READ_WHITELIST = 11,
    WRITE_WHITELIST = 12,
    READ_BLACKLIST = 13,
    WRITE_BLACKLIST = 14,
    READ_AD_HISTORY = 15,


}